name: Deploy with Kamal

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    env:
      WEB_SERVER_IP: ${{ secrets.WEB_SERVER_IP }}
      GITLAB_REGISTRY_ACCESS_TOKEN: ${{ secrets.GITLAB_REGISTRY_ACCESS_TOKEN }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Install Kamal
      run: gem install kamal -v 2.5.2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy with Kamal
      run: kamal deploy
